import { beforeEach, describe, expect, it, vi } from 'vitest'
const api = vi.hoisted(() => ({ simulateNextMatchOnBranch: vi.fn(), simulateNextRoundOnBranch: vi.fn(), simulateNextWeekOnBranch: vi.fn(), simulateNextTournamentOnBranch: vi.fn(), simulateFullSeasonOnBranch: vi.fn(), simulateWorldTourFinalsOnBranch: vi.fn() }))
vi.mock('../api/client', () => api)
import { executeBranchSimulation, validExecutionResponse } from './branchSimulation'
beforeEach(() => { vi.clearAllMocks(); Object.values(api).forEach(mock => mock.mockResolvedValue({})) })
describe('branch simulation contracts', () => {
  it.each([['next_match','simulateNextMatchOnBranch'],['next_round','simulateNextRoundOnBranch'],['next_week','simulateNextWeekOnBranch'],['next_tournament','simulateNextTournamentOnBranch'],['full_season','simulateFullSeasonOnBranch'],['world_tour_finals','simulateWorldTourFinalsOnBranch']] as const)('dispatches %s to %s', async (action, client) => { const payload = { expected_head_checkpoint_id:'cp-a',command_id:'cmd',audit_reason:'reason',explicit_confirmation:true }; await executeBranchSimulation(action,'run-a','branch-a',payload); expect(api[client]).toHaveBeenCalledWith('run-a','branch-a',payload); expect(Object.values(api).filter(mock => mock.mock.calls.length)).toHaveLength(1) })
  it('rejects malformed Full Season summaries', () => { const value:any={product_run_id:'run-a',branch_id:'branch-a',previous_head_checkpoint_id:'cp-a',new_head_checkpoint_id:'cp-b',official_branch_changed:false,simulation_result:{mode:'simulate_full_season',completed_in_command_count:1,completed_week_group_count:-1,season_complete:true}}; expect(validExecutionResponse(value,'full_season','run-a','branch-a','cp-a')).toBe(false) })
  it('rejects malformed Finals provenance', () => { const value:any={product_run_id:'run-a',branch_id:'branch-a',previous_head_checkpoint_id:'cp-a',new_head_checkpoint_id:'cp-b',official_branch_changed:false,legacy_simulation_run_id:'legacy-a',previous_season:1,current_season:1,previous_week:1,current_week:1,previous_event_id:null,current_event_id:null,previous_event_sequence:null,current_event_sequence:null,finals:{run_id:'wrong',already_simulated:false}}; expect(validExecutionResponse(value,'world_tour_finals','run-a','branch-a','cp-a')).toBe(false) })
})

describe('action-specific response validation', () => {
  const common = { product_run_id: 'run-a', branch_id: 'branch-a', legacy_simulation_run_id: 'legacy-a', previous_head_checkpoint_id: 'cp-a', new_head_checkpoint_id: 'cp-b', official_branch_changed: false }
  it('accepts a valid Full Season summary', () => { const value:any={...common,simulation_result:{mode:'simulate_full_season',completed_in_command_count:4,completed_week_group_count:2,season_complete:true}}; expect(validExecutionResponse(value,'full_season','run-a','branch-a','cp-a')).toBe(true) })
  it('accepts a valid World Tour Finals response', () => { const qualification={target_season:2030,qualifier_count:1,reserve_count:0,qualified:[],reserves:[],ineligible_race_entries:[]}; const value:any={...common,previous_season:2030,current_season:2030,previous_week:61,current_week:61,previous_event_id:null,current_event_id:null,previous_event_sequence:null,current_event_sequence:null,finals:{run_id:'legacy-a',season:2030,event_id:'finals',already_simulated:false,qualification:{run_id:'legacy-a',season:2030,source_as_of_season:2030,source_as_of_week:61,qualification},result:{run_id:'legacy-a',season:2030,event_id:'finals',source_as_of_season:2030,source_as_of_week:61,result:{event_id:'finals',season:2030,qualification,groups:[],knockout:[],placements:[]}}}}; expect(validExecutionResponse(value,'world_tour_finals','run-a','branch-a','cp-a')).toBe(true) })
  it.each([['product_run_id','wrong'],['branch_id','wrong'],['previous_head_checkpoint_id','wrong'],['official_branch_changed',true]])('rejects wrong common %s', (field,value) => { const response:any={...common,[field]:value,simulation_result:{mode:'simulate_next_match'}}; expect(validExecutionResponse(response,'next_match','run-a','branch-a','cp-a')).toBe(false) })
  it('rejects the wrong mode', () => { const value:any={...common,simulation_result:{mode:'simulate_next_round'}}; expect(validExecutionResponse(value,'next_match','run-a','branch-a','cp-a')).toBe(false) })
})
