"""SQLite persistence adapters and schema models."""

from beta_engine.infrastructure.db.engine import DatabaseSettings, create_session_factory, create_sqlite_engine
from beta_engine.infrastructure.db.repositories import (
    NextSeasonPlayerRecord,
    PersistedGeneratedPlayerProvenanceRecord,
    PersistedRunTalentCountryAllocationRecord,
    PersistedRunTalentPlanRecord,
    RunProspectRecord,
    deterministic_prospect_id,
    PersistedPlayerTransitionRecord,
    PersistedSeasonRolloverRecord,
    RunLineageRecord,
    RunContainerRecord,
    RunBranchRecord,
    BranchExecutionTarget,
    BranchExecutionTargetResolutionError,
    BranchExecutionTargetNotFoundError, BranchExecutionTargetConflictError,
    BranchSimulateNextMatchCommand, BranchSimulateNextMatchResult,
    BranchSimulateNextRoundCommand, BranchSimulateNextRoundResult,
    BranchSimulateNextWeekCommand, BranchSimulateNextWeekResult,
    BranchSimulateNextTournamentCommand, BranchSimulateNextTournamentResult,
    BranchSimulateFullSeasonCommand, BranchSimulateFullSeasonResult,
    BranchSimulateWorldTourFinalsCommand, BranchSimulateWorldTourFinalsResult,
    ReviewedFinalsPhaseDescriptor,
    BranchSimulationError, BranchSimulationValidationError, BranchSimulationConflictError,
    BranchSimulationIdempotencyConflictError,
    ViewerOfficialRunContext,
    ViewerOfficialRunContextNotFoundError,
    ViewerOfficialRunContextConflictError,
    LegacyRunCloneInventory,
    LegacyRunCloneInventorySection,
    LegacyRunClonePreflightResult,
    LegacyRunClonePreflightError,
    LegacyRunCloneResult,
    LegacyRunCloneSectionResult,
    LegacyRunCloneError,
    UnsafeLegacyRunCloneSourceError,
    LegacyRunCloneTargetExistsError,
    ForkRunBranchCommand,
    ForkRunBranchResult,
    BranchForkError,
    BranchForkValidationError,
    BranchForkTargetExistsError,
    BranchForkIdempotencyConflictError,
    BranchForkSourceStateMismatchError,
    SetOfficialRunBranchCommand,
    SetOfficialRunBranchResult,
    OfficialBranchSelectionValidationError,
    OfficialBranchSelectionConflictError,
    OfficialBranchSelectionIdempotencyConflictError,
    OfficialBranchSelectionStateMismatchError,
    UnsupportedCloneSourceError,
    BranchCheckpointRecord,
    RunBranchStateRecord,
    SimulationPersistenceRepository,
    SimulationRunInfo,
)

__all__ = [
    "DatabaseSettings",
    "NextSeasonPlayerRecord",
    "PersistedGeneratedPlayerProvenanceRecord",
    "PersistedPlayerTransitionRecord",
    "PersistedRunTalentCountryAllocationRecord",
    "PersistedRunTalentPlanRecord",
    "RunProspectRecord",
    "deterministic_prospect_id",
    "PersistedSeasonRolloverRecord",
    "RunLineageRecord",
    "RunContainerRecord",
    "RunBranchRecord",
    "BranchExecutionTarget",
    "BranchExecutionTargetResolutionError",
    "BranchExecutionTargetNotFoundError", "BranchExecutionTargetConflictError",
    "BranchSimulateNextMatchCommand", "BranchSimulateNextMatchResult",
    "BranchSimulateNextRoundCommand", "BranchSimulateNextRoundResult",
    "BranchSimulateNextWeekCommand", "BranchSimulateNextWeekResult",
    "BranchSimulateNextTournamentCommand", "BranchSimulateNextTournamentResult",
    "BranchSimulateFullSeasonCommand", "BranchSimulateFullSeasonResult",
    "BranchSimulateWorldTourFinalsCommand", "BranchSimulateWorldTourFinalsResult",
    "ReviewedFinalsPhaseDescriptor",
    "BranchSimulationError", "BranchSimulationValidationError", "BranchSimulationConflictError",
    "BranchSimulationIdempotencyConflictError",
    "ViewerOfficialRunContext",
    "ViewerOfficialRunContextNotFoundError",
    "ViewerOfficialRunContextConflictError",
    "LegacyRunCloneInventory",
    "LegacyRunCloneInventorySection",
    "LegacyRunClonePreflightResult",
    "LegacyRunClonePreflightError",
    "LegacyRunCloneResult",
    "LegacyRunCloneSectionResult",
    "LegacyRunCloneError",
    "UnsafeLegacyRunCloneSourceError",
    "LegacyRunCloneTargetExistsError",
    "ForkRunBranchCommand",
    "ForkRunBranchResult",
    "BranchForkError",
    "BranchForkValidationError",
    "BranchForkTargetExistsError",
    "BranchForkIdempotencyConflictError",
    "BranchForkSourceStateMismatchError",
    "SetOfficialRunBranchCommand", "SetOfficialRunBranchResult",
    "OfficialBranchSelectionValidationError", "OfficialBranchSelectionConflictError",
    "OfficialBranchSelectionIdempotencyConflictError", "OfficialBranchSelectionStateMismatchError",
    "UnsupportedCloneSourceError",
    "BranchCheckpointRecord",
    "RunBranchStateRecord",
    "SimulationPersistenceRepository",
    "SimulationRunInfo",
    "create_session_factory",
    "create_sqlite_engine",
]
