"""Domain package exports by bounded context."""

from beta_engine.domain.countries import CountriesConfig, Country, CountryTalentModel
from beta_engine.domain.players import HiddenCareerTraits, Player, PlayerGenerator
from beta_engine.domain.draws import (
    DrawEngine,
    DrawEntrantType,
    DrawNode,
    DrawSlot,
    DrawType,
    GeneratedDraw,
    LuckyLoserHook,
)
from beta_engine.domain.matches import (
    MatchContext,
    MatchEngine,
    MatchParticipantContext,
    MatchResult,
    MatchTerminationReason,
    RetirementRule,
    RetirementTrigger,
    SetResult,
)

from beta_engine.domain.finals import (
    FinalsEngine,
    FinalsGroup,
    FinalsGroupMatch,
    FinalsGroupSlot,
    FinalsGroupStandingEntry,
    FinalsKnockoutMatch,
    FinalsPlacement,
    FinalsQualificationResult,
    FinalsQualifiedPlayer,
    FinalsResult,
)

from beta_engine.domain.entries import (
    AcceptanceList,
    AcceptanceStatus,
    EntryDecision,
    EntryEngine,
    EntryTarget,
    EntryTuningConfig,
    TournamentEntry,
)
from beta_engine.domain.rankings import (
    CompletedTournamentPointsInput,
    PlayerRaceEntry,
    PlayerRankingEntry,
    RaceTable,
    RankedResultContribution,
    RankingRaceEngine,
    RankingRaceReport,
    RankingTable,
    TournamentPointAward,
)

from beta_engine.domain.tournaments import (
    CalendarEvent,
    LuckyLoserRules,
    SeasonCalendar,
    TournamentPointDistribution,
    TournamentTemplate,
    TournamentTemplatesConfig,
    validate_calendar_template_references,
)

__all__ = [
    "CountriesConfig",
    "Country",
    "CountryTalentModel",
    "HiddenCareerTraits",
    "Player",
    "PlayerGenerator",
    "DrawEngine",
    "DrawEntrantType",
    "DrawNode",
    "DrawSlot",
    "DrawType",
    "GeneratedDraw",
    "LuckyLoserHook",
    "MatchContext",
    "MatchEngine",
    "MatchParticipantContext",
    "MatchResult",
    "MatchTerminationReason",
    "RetirementRule",
    "RetirementTrigger",
    "SetResult",
    "FinalsEngine",
    "FinalsGroup",
    "FinalsGroupMatch",
    "FinalsGroupSlot",
    "FinalsGroupStandingEntry",
    "FinalsKnockoutMatch",
    "FinalsPlacement",
    "FinalsQualificationResult",
    "FinalsQualifiedPlayer",
    "FinalsResult",
    "AcceptanceList",
    "AcceptanceStatus",
    "EntryDecision",
    "EntryEngine",
    "EntryTarget",
    "EntryTuningConfig",
    "TournamentEntry",
    "CompletedTournamentPointsInput",
    "PlayerRaceEntry",
    "PlayerRankingEntry",
    "RaceTable",
    "RankedResultContribution",
    "RankingRaceEngine",
    "RankingRaceReport",
    "RankingTable",
    "TournamentPointAward",
    "CalendarEvent",
    "LuckyLoserRules",
    "SeasonCalendar",
    "TournamentPointDistribution",
    "TournamentTemplate",
    "TournamentTemplatesConfig",
    "validate_calendar_template_references",
]
