import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { render, screen, waitFor } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { useState } from 'react'
import { MemoryRouter, Route, Routes } from 'react-router-dom'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import { adminBranchStateQueryKey } from '../admin/adminQueryKeys'
import { RunSimulationPage } from './RunSimulationPage'

const context = vi.hoisted(() => ({ value: null as any, time: { mode: 'present' } as any }))
const api = vi.hoisted(() => ({ getRunContainer: vi.fn(), getBranchState: vi.fn(), getBranchCheckpoint: vi.fn(), simulateNextMatchOnBranch: vi.fn(), simulateNextRoundOnBranch: vi.fn(), simulateNextWeekOnBranch: vi.fn(), simulateNextTournamentOnBranch: vi.fn(), simulateFullSeasonOnBranch: vi.fn(), simulateWorldTourFinalsOnBranch: vi.fn(), makeOfficialRunBranch: vi.fn() }))
vi.mock('../admin/AdminBranchContext', () => ({ useAdminBranch: () => context.value }))
vi.mock('../admin/AdminTimeContext', () => ({ useAdminTime: () => context.time }))
vi.mock('../api/client', () => api)

const branch = (id: string, head: string, readOnly = false) => ({ branch_id: id, run_id: 'run-a', display_name: id === 'branch-a' ? 'Branch A' : 'Branch B', status: 'active', read_only: readOnly, branch_seed: 1, legacy_simulation_run_id: `legacy-${id}`, forked_from_branch_id: null, forked_from_checkpoint_id: null, head_checkpoint_id: head, is_official: id === 'branch-a' })
const state = (id: string, head: string) => ({ branch_id: id, run_id: 'run-a', head_checkpoint_id: head, current_season: id === 'branch-a' ? 2004 : 2005, current_week: id === 'branch-a' ? 17 : 18, current_event_id: `event-${id}`, current_event_sequence: 2, state_schema_version: '1', status: 'active', metadata_json: {} })
const checkpoint = (id: string, branchId: string) => ({ checkpoint_id: id, run_id: 'run-a', branch_id: branchId, kind: 'initial' })
const response = (branchId = 'branch-a', previous = 'cp-a') => ({ product_run_id: 'run-a', branch_id: branchId, legacy_simulation_run_id: `legacy-${branchId}`, previous_head_checkpoint_id: previous, new_head_checkpoint_id: `${previous}-next`, official_branch_changed: false, simulation_result: { mode: 'simulate_next_match' } })
function select(id: string, head: string, viewerBranchId = 'branch-a', readOnly = false) { context.value = { selectedBranchId: id, selectedBranch: branch(id, head, readOnly), viewerBranchId, branches: [branch('branch-a', 'cp-a'), branch('branch-b', 'cp-b')], runId: 'run-a' } }
function renderHarness() {
  const client = new QueryClient({ defaultOptions: { queries: { retry: false } } })
  function Harness() { const [, refresh] = useState(0); return <><button onClick={() => { select('branch-b', 'cp-b'); refresh(value => value + 1) }}>Switch to B</button><button onClick={() => { select('branch-a', 'cp-b'); client.setQueryData(adminBranchStateQueryKey('run-a', 'branch-a'), state('branch-a', 'cp-b')); refresh(value => value + 1) }}>Advance head</button><RunSimulationPage /></> }
  return { client, ...render(<QueryClientProvider client={client}><MemoryRouter initialEntries={['/admin/runs/run-a/simulate']}><Routes><Route path="/admin/runs/:runId/simulate" element={<Harness />} /></Routes></MemoryRouter></QueryClientProvider>) }
}
async function submitNextMatch() { await userEvent.click(await screen.findByRole('button', { name: 'Next Match' })); const command = screen.getByLabelText('Simulation command ID').textContent; await userEvent.type(screen.getByLabelText('Simulation audit reason'), ' reviewed reason '); await userEvent.click(screen.getByLabelText('Confirm simulation')); await userEvent.click(screen.getByRole('button', { name: 'Confirm Simulate Next Match' })); return command }
beforeEach(() => { vi.clearAllMocks(); context.time = { mode: 'present' }; select('branch-a', 'cp-a'); api.getRunContainer.mockResolvedValue({ run_id: 'run-a', display_name: 'Run A', status: 'active', read_only: false, storage_kind: 'custom_local' }); api.getBranchState.mockImplementation((id: string) => Promise.resolve(state(id, id === 'branch-a' ? context.value.selectedBranch.head_checkpoint_id : 'cp-b'))); api.getBranchCheckpoint.mockImplementation((id: string) => Promise.resolve(checkpoint(id, id === 'cp-a' ? 'branch-a' : id === 'cp-b' && context.value.selectedBranchId === 'branch-a' ? 'branch-a' : 'branch-b'))); api.simulateNextMatchOnBranch.mockResolvedValue(response()) })

describe('RunSimulationPage', () => {
  it('shows the coherent Active Admin Branch target', async () => { renderHarness(); expect(await screen.findByText('Run: Run A')).toBeInTheDocument(); expect(await screen.findByText('cp-a')).toBeInTheDocument(); for (const text of ['Branch A (branch-a)', '2004', 'W17', 'event-branch-a']) expect(screen.getByText(text)).toBeInTheDocument() })
  it('submits the exact reviewed Next Match snapshot', async () => { renderHarness(); const command = await submitNextMatch(); await waitFor(() => expect(api.simulateNextMatchOnBranch).toHaveBeenCalledWith('run-a', 'branch-a', { expected_head_checkpoint_id: 'cp-a', command_id: command, audit_reason: 'reviewed reason', explicit_confirmation: true })) })
  it('keeps a historical View checkpoint separate from the mutation target', async () => { context.time = { mode: 'checkpoint', viewSeason: 2003, viewWeek: 9, viewCheckpointId: 'cp-old' }; renderHarness(); const command = await submitNextMatch(); expect(screen.getByText(/Past · S2003 · W9 · cp-old/)).toBeInTheDocument(); await waitFor(() => expect(api.simulateNextMatchOnBranch).toHaveBeenCalledWith('run-a', 'branch-a', { expected_head_checkpoint_id: 'cp-a', command_id: command, audit_reason: 'reviewed reason', explicit_confirmation: true })); expect(api.simulateNextMatchOnBranch).not.toHaveBeenCalledWith('run-a', 'branch-a', expect.objectContaining({ expected_head_checkpoint_id: 'cp-old' })) })
  it('clears an open Branch A review when the Active Admin Branch switches to B', async () => { renderHarness(); await userEvent.click(await screen.findByRole('button', { name: 'Next Match' })); expect(screen.getByText('Review Next Match')).toBeInTheDocument(); await userEvent.click(screen.getByRole('button', { name: 'Switch to B' })); expect(await screen.findByText('Branch B (branch-b)')).toBeInTheDocument(); expect(screen.queryByText('Review Next Match')).not.toBeInTheDocument(); expect(api.simulateNextMatchOnBranch).not.toHaveBeenCalled() })
  it('blocks submission when the coherent head changes after review', async () => { renderHarness(); await userEvent.click(await screen.findByRole('button', { name: 'Next Match' })); await userEvent.type(screen.getByLabelText('Simulation audit reason'), 'reason'); await userEvent.click(screen.getByLabelText('Confirm simulation')); await userEvent.click(screen.getByRole('button', { name: 'Advance head' })); expect(await screen.findByText(/head changed/i)).toBeInTheDocument(); expect(screen.getByRole('button', { name: 'Confirm Simulate Next Match' })).toBeDisabled(); expect(api.simulateNextMatchOnBranch).not.toHaveBeenCalled() })
  it('requires a new review and command after HTTP 409 without retrying', async () => { api.simulateNextMatchOnBranch.mockRejectedValueOnce({ status: 409 }); renderHarness(); const oldCommand = await submitNextMatch(); expect(await screen.findByText(/execution state changed/i)).toBeInTheDocument(); expect(screen.queryByText('Review Next Match')).not.toBeInTheDocument(); expect(api.simulateNextMatchOnBranch).toHaveBeenCalledTimes(1); await userEvent.click(screen.getByRole('button', { name: 'Next Match' })); expect(screen.getByLabelText('Simulation command ID')).not.toHaveTextContent(oldCommand ?? '') })
  it('does not render an old Branch A success after switching to Branch B in flight', async () => { let resolve!: (value: any) => void; api.simulateNextMatchOnBranch.mockReturnValueOnce(new Promise(value => { resolve = value })); const invalidate = vi.spyOn(QueryClient.prototype, 'invalidateQueries'); renderHarness(); await submitNextMatch(); await userEvent.click(screen.getByRole('button', { name: 'Switch to B' })); expect(await screen.findByText('Branch B (branch-b)')).toBeInTheDocument(); resolve(response('branch-a', 'cp-a')); await waitFor(() => expect(invalidate).toHaveBeenCalledWith(expect.objectContaining({ queryKey: ['admin-run-branches', 'run-a'] }))); expect(screen.queryByText(/advanced branch-a/i)).not.toBeInTheDocument(); expect(screen.queryByText('cp-a-next')).not.toBeInTheDocument(); expect(api.simulateNextMatchOnBranch).toHaveBeenCalledTimes(1) })
  it('hides an old Branch A HTTP 500 after switching to Branch B in flight', async () => { let reject!: (value: any) => void; api.simulateNextMatchOnBranch.mockReturnValueOnce(new Promise((_resolve, failure) => { reject = failure })); renderHarness(); await submitNextMatch(); await userEvent.click(screen.getByRole('button', { name: 'Switch to B' })); reject(new Error('Branch A exploded')); await waitFor(() => expect(screen.getByText('Branch B (branch-b)')).toBeInTheDocument()); expect(screen.queryByText('Branch A exploded')).not.toBeInTheDocument() })
  it('does not invalidate Viewer reads when a non-Viewer Branch advances', async () => { select('branch-b', 'cp-b', 'branch-a'); api.simulateNextMatchOnBranch.mockResolvedValue(response('branch-b', 'cp-b')); const invalidate = vi.spyOn(QueryClient.prototype, 'invalidateQueries'); renderHarness(); await submitNextMatch(); await waitFor(() => expect(api.simulateNextMatchOnBranch).toHaveBeenCalledWith('run-a', 'branch-b', expect.anything())); expect(api.makeOfficialRunBranch).not.toHaveBeenCalled(); expect(invalidate).not.toHaveBeenCalledWith({ queryKey: ['viewer-official-run-context', 'run-a'] }) })
  it('invalidates Viewer reads without changing its pointer when the Viewer Branch advances', async () => { const invalidate = vi.spyOn(QueryClient.prototype, 'invalidateQueries'); renderHarness(); await submitNextMatch(); await waitFor(() => expect(invalidate).toHaveBeenCalledWith({ queryKey: ['viewer-official-run-context', 'run-a'] })); expect(api.makeOfficialRunBranch).not.toHaveBeenCalled(); expect(context.value.viewerBranchId).toBe('branch-a') })
  it('shows a read-only target and disables actions', async () => { select('branch-a', 'cp-a', 'branch-a', true); renderHarness(); expect(await screen.findByText('Simulation blocked: Branch is read-only.')).toBeInTheDocument(); expect(screen.getByRole('button', { name: 'Next Match' })).toBeDisabled() })
  it('blocks mismatched BranchState identity', async () => { api.getBranchState.mockResolvedValue({ ...state('branch-a', 'cp-a'), branch_id: 'wrong' }); renderHarness(); expect(await screen.findByText('Simulation blocked: BranchState is missing.')).toBeInTheDocument(); expect(api.simulateNextMatchOnBranch).not.toHaveBeenCalled() })
})
