import { screen, waitFor } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import { renderWithRoute } from '../test/testUtils'
import { RunSimulationPage } from './RunSimulationPage'
const context=vi.hoisted(()=>({value:null as any})); const api=vi.hoisted(()=>({getRunContainer:vi.fn(),getBranchState:vi.fn(),getBranchCheckpoint:vi.fn(),simulateNextMatchOnBranch:vi.fn(),simulateNextRoundOnBranch:vi.fn(),simulateNextWeekOnBranch:vi.fn(),simulateNextTournamentOnBranch:vi.fn(),simulateFullSeasonOnBranch:vi.fn(),simulateWorldTourFinalsOnBranch:vi.fn()})); vi.mock('../admin/AdminBranchContext',()=>({useAdminBranch:()=>context.value})); vi.mock('../api/client',()=>api)
const branch=(read_only=false)=>({branch_id:'branch-a',run_id:'run-a',display_name:'Branch A',status:'active',read_only,branch_seed:1,legacy_simulation_run_id:'legacy-a',forked_from_branch_id:null,forked_from_checkpoint_id:null,head_checkpoint_id:'cp-a',is_official:false}); const state={branch_id:'branch-a',run_id:'run-a',head_checkpoint_id:'cp-a',current_season:2004,current_week:17,current_event_id:'event-a',current_event_sequence:2,state_schema_version:'1',status:'active',metadata_json:{}}; const checkpoint={checkpoint_id:'cp-a',run_id:'run-a',branch_id:'branch-a',kind:'initial'}; const response={product_run_id:'run-a',branch_id:'branch-a',legacy_simulation_run_id:'legacy-a',previous_head_checkpoint_id:'cp-a',new_head_checkpoint_id:'cp-b',official_branch_changed:false,simulation_result:{mode:'simulate_next_match'}}
function setup(readonly=false){context.value={selectedBranchId:'branch-a',selectedBranch:branch(readonly),viewerBranchId:'viewer',branches:[branch(readonly)],runId:'run-a'};api.getRunContainer.mockResolvedValue({run_id:'run-a',display_name:'Run A',status:'active',read_only:false,storage_kind:'custom_local'});api.getBranchState.mockResolvedValue(state);api.getBranchCheckpoint.mockResolvedValue(checkpoint);api.simulateNextMatchOnBranch.mockResolvedValue(response)} beforeEach(()=>{vi.clearAllMocks();setup()})
describe('RunSimulationPage',()=>{
 it('shows the coherent Active Admin Branch target',async()=>{renderWithRoute(<RunSimulationPage/>,'/admin/runs/run-a/simulate');expect(await screen.findByText('Run: Run A')).toBeInTheDocument();expect(await screen.findByText('cp-a')).toBeInTheDocument();for(const text of ['Branch A (branch-a)','2004','W17','event-a'])expect(screen.getByText(text)).toBeInTheDocument()})
 it('submits the exact reviewed Next Match snapshot',async()=>{renderWithRoute(<RunSimulationPage/>,'/admin/runs/run-a/simulate');await userEvent.click(await screen.findByRole('button',{name:'Next Match'}));const command=screen.getByLabelText('Simulation command ID').textContent;await userEvent.type(screen.getByLabelText('Simulation audit reason'),' reviewed reason ');await userEvent.click(screen.getByLabelText('Confirm simulation'));await userEvent.click(screen.getByRole('button',{name:'Confirm Simulate Next Match'}));await waitFor(()=>expect(api.simulateNextMatchOnBranch).toHaveBeenCalledWith('run-a','branch-a',{expected_head_checkpoint_id:'cp-a',command_id:command,audit_reason:'reviewed reason',explicit_confirmation:true}))})
 it('shows read-only target and disables actions',async()=>{setup(true);renderWithRoute(<RunSimulationPage/>,'/admin/runs/run-a/simulate');expect(await screen.findByText('Simulation blocked: Branch is read-only.')).toBeInTheDocument();expect(screen.getByRole('button',{name:'Next Match'})).toBeDisabled()})
 it('blocks mismatched BranchState identity',async()=>{api.getBranchState.mockResolvedValue({...state,branch_id:'wrong'});renderWithRoute(<RunSimulationPage/>,'/admin/runs/run-a/simulate');expect(await screen.findByText('Simulation blocked: BranchState is missing.')).toBeInTheDocument();expect(api.simulateNextMatchOnBranch).not.toHaveBeenCalled()})
})
