import { fireEvent, screen, waitFor } from '@testing-library/react'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import { ViewerRunSelector } from './ViewerRunSelector'
import { LAST_RUN_ID_STORAGE_KEY, VIEWER_ACTIVE_RUN_STORAGE_KEY } from '../viewer/activeRun'
import { VIEWER_ACTIVE_PRODUCT_RUN_STORAGE_KEY } from '../viewer/activeProductRun'
import { renderWithViewerProviders } from '../test/viewerTestUtils'
const api = vi.hoisted(() => ({ listRunContainers: vi.fn(), getViewerOfficialRunContext: vi.fn(), ApiError: class ApiError extends Error { constructor(message: string, public status: number) { super(message) } } }))
vi.mock('../api/client', () => api)
const context = { product_run_id: 'product-a', product_run_display_name: 'Product A', product_run_status: 'inactive', product_run_storage_kind: 'built_in', product_run_read_only: true, official_branch_id: 'branch-a', official_branch_display_name: 'Official A', official_branch_status: 'active', official_branch_read_only: true, official_branch_seed: null, legacy_simulation_run_id: 'legacy-a', head_checkpoint_id: 'cp', head_checkpoint_kind: 'current', current_season: 2030, current_week: 2, current_event_id: null, current_event_sequence: null, resolution_version: 'v1' }
describe('ViewerRunSelector Product Run bridge', () => { beforeEach(() => { localStorage.clear(); vi.clearAllMocks(); api.listRunContainers.mockResolvedValue({ run_containers: [{ run_id: 'product-a', display_name: 'Product A', status: 'inactive', storage_kind: 'built_in', read_only: true }] }); api.getViewerOfficialRunContext.mockResolvedValue(context) }); it('lists Product Runs and resolves before persisting the legacy bridge', async () => { renderWithViewerProviders(<ViewerRunSelector />); const select = await screen.findByLabelText('Available Product Runs'); expect(await screen.findByRole('option', { name: /Product A.*product-a.*inactive.*built_in.*read-only/ })).toBeInTheDocument(); fireEvent.change(select, { target: { value: 'product-a' } }); expect(api.getViewerOfficialRunContext).not.toHaveBeenCalled(); fireEvent.click(screen.getByRole('button', { name: 'Set active run' })); await waitFor(() => expect(localStorage.getItem(VIEWER_ACTIVE_PRODUCT_RUN_STORAGE_KEY)).toBe('product-a')); expect(localStorage.getItem(VIEWER_ACTIVE_RUN_STORAGE_KEY)).toBe('legacy-a'); expect(localStorage.getItem(LAST_RUN_ID_STORAGE_KEY)).toBe('legacy-a'); expect(screen.getByText(/Official A/)).toBeInTheDocument() }); it('preserves both selections when official context resolution fails', async () => { localStorage.setItem(VIEWER_ACTIVE_PRODUCT_RUN_STORAGE_KEY, 'old-product'); localStorage.setItem(VIEWER_ACTIVE_RUN_STORAGE_KEY, 'old-legacy'); api.getViewerOfficialRunContext.mockRejectedValue(new api.ApiError('no coherent official Branch', 409)); renderWithViewerProviders(<ViewerRunSelector />); const select = await screen.findByLabelText('Available Product Runs'); fireEvent.change(select, { target: { value: 'product-a' } }); fireEvent.click(screen.getByRole('button', { name: 'Set active run' })); expect(await screen.findByText('no coherent official Branch')).toBeInTheDocument(); expect(localStorage.getItem(VIEWER_ACTIVE_PRODUCT_RUN_STORAGE_KEY)).toBe('old-product'); expect(localStorage.getItem(VIEWER_ACTIVE_RUN_STORAGE_KEY)).toBe('old-legacy') }) })
